{
 "title": "Quatt - Perfomance",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "COP Trend",
   "type": "xychart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "cop = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_1_quatt_cop\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"cop\"})\r\n\r\nbuiten = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_feels_like_temperature\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)\r\n  |> rename(columns: {_value: \"buiten\"})\r\n\r\njoin(tables: {cop: cop, buiten: buiten}, on: [\"_time\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      buiten: r.buiten,\r\n      cop: r.cop\r\n  }))"
    }
   ]
  },
  {
   "title": "COP Quat Combined",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "query": "cop1 = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_1_quatt_cop\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"COP WP1\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])\r\n\r\ncop2 = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_2_quatt_cop\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"COP WP2\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])\r\n\r\nunion(tables: [cop1, cop2])"
    }
   ]
  },
  {
   "title": "Power Input / Outdoor Temperature",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "query": "wp1 = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_1_power_input\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Vermogen WP1 (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])\r\n\r\nwp2 = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_2_power_input\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Vermogen WP2 (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])\r\n\r\nbuiten = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_feels_like_temperature\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Buitentemperatuur (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])\r\n\r\nunion(tables: [wp1, wp2, buiten])"
    }
   ]
  },
  {
   "title": "Delta T en flowrate",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "query": "delta1 = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_1_water_delta\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Delta T WP1 (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])\r\n\r\ndelta2 = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_2_water_delta\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Delta T WP2 (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])\r\n\r\nflow = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"flowmeter_flowrate\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Flowrate (L/min)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])\r\n\r\nunion(tables: [delta1, delta2, flow])"
    }
   ]
  },
  {
   "title": "In-output temperatures",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_1_temperature_water_out\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Aanvoer WP1 (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_1_temperature_water_in\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Retour WP1 (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_2_temperature_water_out\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Aanvoer WP2 (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"heatpump_2_temperature_water_in\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Retour WP2 (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  }
 ]
}