{
 "title": "Weather Station",
 "description": "Weather Station",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature & Comfort",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_outdoor_temperature\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Buitentemperatuur (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_feels_like_temperature\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Feels like (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_dewpoint\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Dauwpunt (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_windchill\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Windchill (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_indoor_temperature\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Binnentemperatuur (°C)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_wind_speed\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Windsnelheid (km/h)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_wind_gust\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Windstoten (km/h)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_max_daily_gust\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Max windstoot dag (km/h)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  },
  {
   "title": "Solar & UV",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_solar_radiation\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Solar radiation (W/m²)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_uv_index\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"UV index\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  },
  {
   "title": "Rain",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_hourly_rain_rate\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Neerslag per uur (mm)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_daily_rain_rate\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Dagelijks totaal (mm)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_rain_rate\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Neerslagintensiteit (mm/h)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  },
  {
   "title": "Air pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_absolute_pressure\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Absolute druk (hPa)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"ws2900_v2_01_18_relative_pressure\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Relatieve druk (hPa)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  }
 ]
}