{
 "title": "Battery - HA-Velp",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Total Power",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r.entity_id == \"marstek_venus_modbus_stored_energy\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()\r\n  |> map(fn: (r) => ({r with _value: r._value / 5.12 * 100.0}))\r\n  |> set(key: \"_field\", value: \"Marstek (%)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r.entity_id == \"marstek_venus_modbus_stored_energy\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()\r\n  |> set(key: \"_field\", value: \"Marstek (kWh)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r.entity_id == \"sessy_dn4t_state_of_charge\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()\r\n  |> set(key: \"_field\", value: \"Sessy DN4T (%)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r.entity_id == \"sessy_d9af_state_of_charge\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()\r\n  |> set(key: \"_field\", value: \"Sessy D9AF (%)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r.entity_id == \"sessy_dx3j_state_of_charge\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()\r\n  |> set(key: \"_field\", value: \"Sessy DX3J (%)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: -6h)\r\n  |> filter(fn: (r) => r.entity_id == \"totaal_opgeslagen_energie\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> last()\r\n  |> set(key: \"_field\", value: \"Totaal (kWh)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  },
  {
   "title": "Revenue Generated Marstek",
   "type": "timeseries",
   "description": "Revenue generated with Marstek",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "query": "power = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"marstek_venus_modbus_battery_power\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 5m, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n\r\nprice = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"frank_energie_prices_current_electricity_price_all_in\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 5m, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n\r\njoin(tables: {power: power, price: price}, on: [\"_time\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if r._value_power < 0.0 \r\n              then (r._value_power * -1.0) / 1000.0 * r._value_price * (5.0 / 60.0)\r\n              else 0.0\r\n  }))\r\n  |> cumulativeSum()\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value, _field: \"Marstek opbrengst (€)\"}))\r\n  |> group(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "Sessy Opbrengst",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "power = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r.entity_id == \"sessy_dn4t_power\" or\r\n      r.entity_id == \"sessy_d9af_power\" or\r\n      r.entity_id == \"sessy_dx3j_power\"\r\n  )\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\r\n  |> group(columns: [\"_time\"])\r\n  |> sum()\r\n  |> group()\r\n\r\nprice = from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"frank_energie_prices_current_electricity_price_all_in\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: 5m, fn: last, createEmpty: true)\r\n  |> fill(usePrevious: true)\r\n\r\njoin(tables: {power: power, price: price}, on: [\"_time\"])\r\n  |> map(fn: (r) => ({\r\n      _time: r._time,\r\n      _value: if r._value_power > 0.0\r\n              then r._value_power / 1000.0 * r._value_price * (5.0 / 60.0)\r\n              else 0.0\r\n  }))\r\n  |> cumulativeSum()\r\n  |> map(fn: (r) => ({_time: r._time, _value: r._value, _field: \"Sessy opbrengst (€)\"}))\r\n  |> group(columns: [\"_field\"])"
    }
   ]
  },
  {
   "title": "Sessy State of Charge",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"sessy_dx3j_state_of_charge\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Sessy DX3J SOC (%)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"sessy_d9af_state_of_charge\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Sessy D9AF SOC (%)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"sessy_dn4t_state_of_charge\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Sessy DN4T SOC (%)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"W\")\r\n  |> filter(fn: (r) => r.entity_id == \"envoy_122149071873_current_power_production\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Solar productie (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  },
  {
   "title": "Marstek / Solar Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"W\")\r\n  |> filter(fn: (r) => r.entity_id == \"envoy_122149071873_current_power_production\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Solar productie (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"W\")\r\n  |> filter(fn: (r) => r.entity_id == \"marstek_venus_modbus_battery_power\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Batterij vermogen (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"marstek_venus_modbus_stored_energy\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({r with _value: r._value / 5.12 * 100.0}))\r\n  |> set(key: \"_field\", value: \"Marstek SOC (%)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  },
  {
   "title": "Total Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"p1_meter_3c39e72bdf42_active_power_l1\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Fase 1 (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"p1_meter_3c39e72bdf42_active_power_l2\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Fase 2 (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"p1_meter_3c39e72bdf42_active_power_l3\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Fase 3 (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"p1_meter_3c39e72bdf42_active_power\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Totaal (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  },
  {
   "title": "Frank Stroom Prijzen",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"frank_energie_prices_current_electricity_price_all_in\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n    |> aggregateWindow(every: 1h, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Stroomprijs (€/kWh)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  },
  {
   "title": "Sessy Batteries",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"sessy_dn4t_power\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Sessy DN4T vermogen (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"sessy_d9af_power\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Sessy D9AF vermogen (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r.entity_id == \"sessy_dx3j_power\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Sessy DX3J vermogen (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    },
    {
     "query": "from(bucket: \"homeassistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"W\")\r\n  |> filter(fn: (r) => r.entity_id == \"envoy_122149071873_current_power_production\")\r\n  |> filter(fn: (r) => r._field == \"value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> set(key: \"_field\", value: \"Solar productie (W)\")\r\n  |> drop(columns: [\"domain\", \"entity_id\"])"
    }
   ]
  }
 ]
}